import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('tr'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'tr': {
      'appName': 'Wondertale',
      'appTagline': 'Yapay Zeka Destekli Sihirli Masallar',
      'createStory': 'Masal Oluştur',
      'myLibrary': 'Masal Kütüphanem',
      'subscription': 'Abonelik & Haklar',
      'selectAge': 'Yaş Grubu Seçin',
      'selectTheme': 'Masal Temasını Seçin',
      'selectMood': 'Masal Amacı / Ruh Hali',
      'childNameOptional': 'Çocuğunuzun Adı (Opsiyonel)',
      'childNameHint': 'Örn: Deniz, Ali (Max 30 karakter)',
      'storyLanguage': 'Masal Dili',
      'generateButton': '✨ Masalı Yapay Zekaya Yazdır',
      'generatingTitle': 'Sihirli Masal Kaleme Alınıyor...',
      'generatingSubtitle': 'Yapay zeka peri tozu serpiyor, illüstrasyon çiziliyor!',
      'dailyLimitReached': 'Günlük Masal Limitine Ulaşıldı',
      'dailyLimitDesc': 'Bugünkü ücretsiz masal hakkınız bitti. Reklam izleyerek +1 hak kazanabilir veya Sınırsız Paket satın alabilirsiniz.',
      'watchAdForBonus': '🎬 Reklam İzle (+1 Masal Kazan)',
      'upgradeToUnlimited': '👑 Sınırsız Masal Aboneliği',
      'readStory': 'Masalı Oku',
      'listenStory': 'Sesli Dinle',
      'pauseStory': 'Duraklat',
      'resumeStory': 'Devam Et',
      'stopStory': 'Durdur',
      'speechSpeed': 'Okuma Hızı',
      'noStoriesYet': 'Henüz kaydedilmiş masalınız yok.',
      'startFirstStory': 'İlkiyle Başlayın!',
      'loginGoogle': 'Google ile Giriş Yap',
      'continueGuest': 'Misafir Olarak Devam Et',
      'loginRequired': 'Masallarınızı bulutta saklamak için giriş yapın.',
      'quotaLeft': 'Kalan Günlük Hak: ',
      'unlimitedAccess': 'Sınırsız Paket Aktif',
      'premiumPerks': '• Sınırsız Masal Üretimi\n• Reklamsız Deneyim\n• Tüm Yaş ve Temalara Erişim\n• Yüksek Çözünürlüklü İllüstrasyonlar',
      'subscribeMonthly': 'Aylık ₺49,99 ile Abone Ol',
      'restorePurchases': 'Satın Alımları Geri Yükle',
      'errorTitle': 'Bir Hata Oluştu',
      'tryAgain': 'Tekrar Dene',
      'charLimitExceeded': 'İsim en fazla 30 karakter olabilir.',
      'watchVideoBannerTitle': '🎬 Video İzleyerek Hak Kazan',
      'watchVideoBannerDesc': 'Video izleyerek masal haklarınızı daha çok artırabilirsiniz!',
      'home': 'Ana Sayfa',
      'profile': 'Profil',
      'welcome': 'Hoş Geldin!',
      'recentStories': 'Son Oluşturulanlar',
      'createNewStory': 'Yeni Masal Oluştur',
      'guestUser': 'Misafir Kullanıcı',
      'dailyQuotaTitle': 'Günlük Masal Hakkı',
      'dailyQuotaUnlimitedDesc': 'İstediğin kadar masal oluşturabilirsin! ✨',
      'dailyQuotaDepleted': 'Bugünlük sihrin tükendi!',
      'signOut': 'Çıkış Yap',
      'appLanguage': 'Uygulama Dili',
      'dailyQuotaSub': '2 ücretsiz masal / gün',
    },
    'en': {
      'appName': 'Wondertale',
      'appTagline': 'AI-Powered Magical Bedtime Stories',
      'createStory': 'Create Story',
      'myLibrary': 'My Story Library',
      'subscription': 'Subscription & Quota',
      'selectAge': 'Select Age Group',
      'selectTheme': 'Choose Story Theme',
      'selectMood': 'Choose Goal / Mood',
      'childNameOptional': "Child's Name (Optional)",
      'childNameHint': 'e.g. Leo, Mia (Max 30 chars)',
      'storyLanguage': 'Story Language',
      'generateButton': '✨ Generate Magical Story',
      'generatingTitle': 'Crafting Your Story...',
      'generatingSubtitle': 'The AI pixie dust is weaving words & drawing illustrations!',
      'dailyLimitReached': 'Daily Limit Reached',
      'dailyLimitDesc': "You've reached your free stories for today. Watch a quick ad to get +1 extra story or upgrade to Unlimited.",
      'watchAdForBonus': '🎬 Watch Ad (+1 Extra Story)',
      'upgradeToUnlimited': '👑 Get Unlimited Access',
      'readStory': 'Read Story',
      'listenStory': 'Listen Narration',
      'pauseStory': 'Pause',
      'resumeStory': 'Resume',
      'stopStory': 'Stop',
      'speechSpeed': 'Reading Speed',
      'noStoriesYet': 'No saved stories yet.',
      'startFirstStory': 'Create Your First Story!',
      'loginGoogle': 'Sign In with Google',
      'continueGuest': 'Continue as Guest',
      'loginRequired': 'Sign in to sync your stories across devices.',
      'quotaLeft': 'Daily Quota Remaining: ',
      'unlimitedAccess': 'Unlimited Premium Active',
      'premiumPerks': '• Unlimited Story Generations\n• 100% Ad-Free Experience\n• All Ages & Themes Unlocked\n• High Quality AI Illustrations',
      'subscribeMonthly': 'Subscribe for \$4.99/mo',
      'restorePurchases': 'Restore Purchases',
      'errorTitle': 'An Error Occurred',
      'tryAgain': 'Try Again',
      'charLimitExceeded': 'Name cannot exceed 30 characters.',
      'watchVideoBannerTitle': '🎬 Watch Video for Extra Story',
      'watchVideoBannerDesc': 'Watch a short video to unlock more story quota!',
      'home': 'Home',
      'profile': 'Profile',
      'welcome': 'Welcome!',
      'recentStories': 'Recent Stories',
      'createNewStory': 'Create New Story',
      'guestUser': 'Guest User',
      'dailyQuotaTitle': 'Daily Story Quota',
      'dailyQuotaUnlimitedDesc': 'You can create unlimited stories! ✨',
      'dailyQuotaDepleted': 'Your magic ran out for today!',
      'signOut': 'Sign Out',
      'appLanguage': 'App Language',
      'dailyQuotaSub': '2 free stories / day',
    },
    'de': {
      'appName': 'Wondertale',
      'appTagline': 'KI-gestützte magische Gute-Nacht-Geschichten',
      'createStory': 'Geschichte erstellen',
      'myLibrary': 'Meine Bibliothek',
      'subscription': 'Abonnement & Kontingent',
      'selectAge': 'Altersgruppe wählen',
      'selectTheme': 'Thema wählen',
      'selectMood': 'Ziel / Stimmung wählen',
      'childNameOptional': 'Name des Kindes (Optional)',
      'childNameHint': 'z.B. Lukas, Mia (Max 30 Zeichen)',
      'storyLanguage': 'Sprache der Geschichte',
      'generateButton': '✨ Magische Geschichte erstellen',
      'generatingTitle': 'Geschichtenzauber wird gewoben...',
      'generatingSubtitle': 'Die KI verteilt Feenstaub & zeichnet Illustrationen!',
      'dailyLimitReached': 'Tägliches Limit erreicht',
      'dailyLimitDesc': 'Sie haben Ihre kostenlosen Geschichten für heute aufgebraucht. Sehen Sie eine kurze Werbung für +1 Geschichte oder sichern Sie sich unbegrenzten Zugang.',
      'watchAdForBonus': '🎬 Werbung ansehen (+1 Geschichte)',
      'upgradeToUnlimited': '👑 Unbegrenzten Zugang sichern',
      'readStory': 'Geschichte lesen',
      'listenStory': 'Vorlesen lassen',
      'pauseStory': 'Pause',
      'resumeStory': 'Fortsetzen',
      'stopStory': 'Stopp',
      'speechSpeed': 'Lesegeschwindigkeit',
      'noStoriesYet': 'Noch keine gespeicherten Geschichten.',
      'startFirstStory': 'Erstelle deine erste Geschichte!',
      'loginGoogle': 'Mit Google anmelden',
      'continueGuest': 'Als Gast fortfahren',
      'loginRequired': 'Melde dich an, um deine Geschichten zu synchronisieren.',
      'quotaLeft': 'Verbleibendes Tageskontingent: ',
      'unlimitedAccess': 'Unbegrenztes Premium Aktiv',
      'premiumPerks': '• Unbegrenzte Geschichtenerstellung\n• 100% Werbefreies Erlebnis\n• Alle Altersgruppen & Themen freigeschaltet\n• Hochauflösende KI-Illustrationen',
      'subscribeMonthly': 'Für 4,99 €/Monat abonnieren',
      'restorePurchases': 'Käufe wiederherstellen',
      'errorTitle': 'Ein Fehler ist aufgetreten',
      'tryAgain': 'Erneut versuchen',
      'charLimitExceeded': 'Der Name darf maximal 30 Zeichen lang sein.',
      'watchVideoBannerTitle': '🎬 Video ansehen für Kontingent',
      'watchVideoBannerDesc': 'Sehen Sie ein kurzes Video, um extra Geschichten freizuschalten!',
      'home': 'Startseite',
      'profile': 'Profil',
      'welcome': 'Willkommen!',
      'recentStories': 'Kürzlich erstellte',
      'createNewStory': 'Neue Geschichte erstellen',
      'guestUser': 'Gastbenutzer',
      'dailyQuotaTitle': 'Tägliches Kontingent',
      'dailyQuotaUnlimitedDesc': 'Sie können unbegrenzt Geschichten erstellen! ✨',
      'dailyQuotaDepleted': 'Dein Zauber ist für heute aufgebraucht!',
      'signOut': 'Abmelden',
      'appLanguage': 'App-Sprache',
      'dailyQuotaSub': '2 kostenlose Geschichten / Tag',
    },
    'ar': {
      'appName': 'Wondertale',
      'appTagline': 'قصص سحرية للأطفال بالذكاء الاصطناعي',
      'createStory': 'إنشاء قصة',
      'myLibrary': 'مكتبتي القصصية',
      'subscription': 'الاشتراك والحصة',
      'selectAge': 'اختر الفئة العمرية',
      'selectTheme': 'اختر موضوع القصة',
      'selectMood': 'اختر الهدف / الحالة',
      'childNameOptional': 'اسم الطفل (اختياري)',
      'childNameHint': 'مثال: أحمد، سارة (30 حرفًا كحد أقصى)',
      'storyLanguage': 'لغة القصة',
      'generateButton': '✨ كتابة قصة سحرية بالذكاء الاصطناعي',
      'generatingTitle': 'جاري كتابة القصة السحرية...',
      'generatingSubtitle': 'الذكاء الاصطناعي ينسج الكلمات ويرسم اللوحات!',
      'dailyLimitReached': 'تم الوصول إلى الحد اليومي',
      'dailyLimitDesc': 'لقد استهلكت قصصك المجانية لهذا اليوم. شاهد إعلاناً للحصول على قصة إضافية أو اشترك للحصول على وصول غير محدود.',
      'watchAdForBonus': '🎬 مشاهدة إعلان (+1 قصة)',
      'upgradeToUnlimited': '👑 الحصول على اشتراك غير محدود',
      'readStory': 'قراءة القصة',
      'listenStory': 'استماع للقصة',
      'pauseStory': 'إيقاف مؤقت',
      'resumeStory': 'استئناف',
      'stopStory': 'إيقاف',
      'speechSpeed': 'سرعة القراءة',
      'noStoriesYet': 'لا توجد قصص محفوظة حتى الآن.',
      'startFirstStory': 'ابدأ بإنشاء قصتك الأولى!',
      'loginGoogle': 'تسجيل الدخول باستخدام Google',
      'continueGuest': 'المتابعة كضيف',
      'loginRequired': 'قم بتسجيل الدخول لحفظ قصصك في السحابة.',
      'quotaLeft': 'الحصة اليومية المتبقية: ',
      'unlimitedAccess': 'اشتراك غير محدود نشط',
      'premiumPerks': '• إنشاء قصص بلا حدود\n• تجربة خالية تماماً من الإعلانات\n• فتح جميع الأعمار والمواضيع\n• صور ورسومات عالية الدقة',
      'subscribeMonthly': 'اشترك مقابل \$4.99 شهرياً',
      'restorePurchases': 'استعادة المشتريات',
      'errorTitle': 'حدث خطأ ما',
      'tryAgain': 'إعادة المحاولة',
      'charLimitExceeded': 'يجب ألا يتجاوز الاسم 30 حرفاً.',
      'watchVideoBannerTitle': '🎬 شاهد فيديو للحصول على حصة',
      'watchVideoBannerDesc': 'شاهد فيديواً قصيراً لزيادة رصيدك من القصص!',
      'home': 'الرئيسية',
      'profile': 'الملف الشخصي',
      'welcome': 'أهلاً بك!',
      'recentStories': 'القصص الحديثة',
      'createNewStory': 'إنشاء قصة جديدة',
      'guestUser': 'مستخدم ضيف',
      'dailyQuotaTitle': 'الحصة اليومية للقصص',
      'dailyQuotaUnlimitedDesc': 'يمكنك إنشاء عدد لا محدود من القصص! ✨',
      'dailyQuotaDepleted': 'نفد سحرك لهذا اليوم!',
      'signOut': 'تسجيل الخروج',
      'appLanguage': 'لغة التطبيق',
      'dailyQuotaSub': '2 قصص مجانية / يوم',
    }
  };

  String get(String key) {
    final langCode = locale.languageCode;
    return _localizedValues[langCode]?[key] ?? _localizedValues['en']?[key] ?? _localizedValues['tr']?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['tr', 'en', 'de', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
